### ISSUE TITLE
Resume fine-tuning with adapters

### ISSUE THREAD

**Issue by zepmck** [Lightning-AI/lit-gpt#238] opened 2023-07-06 15:59 UTC
Hi all, is there any way to resume a fine tuning while using adapters? Thanks!

**Comment by carmocca** [comment] 2023-07-06 16:01
We recently added resuming capabilities to the pertaining scripts: #230, #229. If you want to give it a shot, the changes to the fine-tune scripts would be the same

**Comment by carmocca** [comment] 2024-01-19 02:26
Duplicate of #209

**Closed by carmocca** 2024-01-19 02:26 UTC
Labels: enhancement, help wanted, fine-tuning
