### ISSUE TITLE
RuntimeError: cutlassF: no kernel found to launch!

### ISSUE THREAD

**Issue by Never-up** [Lightning-AI/lit-gpt#408] opened 2023-08-15 06:02 UTC
when run 
```bash
python generate/base.py --prompt "Hello, my name is" --checkpoint_dir ./stablelm-base-alpha-3b
```
have **RuntimeError: cutlassF: no kernel found to launch!** error, so ask why please ？i don`t know why 
> Time to instantiate model: 2.10 seconds.
Time to load the model weights: 12.79 seconds.
Global seed set to 1234
Traceback (most recent call last):
  File "/mnt/workspace/lit-gpt/generate/base.py", line 198, in <module>
    CLI(main)
  File "/home/pai/lib/python3.9/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/pai/lib/python3.9/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/mnt/workspace/lit-gpt/generate/base.py", line 169, in main
    y = generate(
  File "/home/pai/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workspace/lit-gpt/generate/base.py", line 64, in generate
    logits = model(x, max_seq_length, input_pos)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workspace/lightning/src/lightning/fabric/wrappers.py", line 117, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workspace/lit-gpt/lit_gpt/model.py", line 99, in forward
    x, self.kv_caches[i] = block(x, (cos, sin), max_seq_length, mask, input_pos, self.kv_caches[i])
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workspace/lit-gpt/lit_gpt/model.py", line 160, in forward
    h, new_kv_cache = self.attn(n_1, rope, max_seq_length, mask, input_pos, kv_cache)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/workspace/lit-gpt/lit_gpt/model.py", line 239, in forward
    y = self.scaled_dot_product_attention(q, k, v, mask=mask)
  File "/mnt/workspace/lit-gpt/lit_gpt/model.py", line 265, in scaled_dot_product_attention
    return torch.nn.functional.scaled_dot_product_attention(
RuntimeError: cutlassF: no kernel found to launch!

**Comment by carmocca** [comment] 2023-08-15 06:29
Duplicate of #327. @Andrei-Aksionov ran some test and seems like you can fix it by installing a different torch version. Which one do you suggest Andrei?

Closing as a duplicate

**Closed by carmocca** 2023-08-15 06:29 UTC

**Comment by Andrei-Aksionov** [comment] 2023-08-15 06:50
Actually it seems like the problem is in the precision (which is `bf16-true` by default) which is not supported by many popular graphics card like T4 or V100.
And previous versions of PyTorch-nightly for some reason didn't care about wrongly provided precision at all.

So try to solve in that order:
1. Use proper precision for your graphics card. [Here](https://github.com/Lightning-AI/lit-gpt/blob/96d66b4845ebe287b5dd57b45e584b38d4f660e7/lit_gpt/speed_monitor.py#L17-L57) you can find what precisions are supported. Hint: use `--precision` CLI argument in order to use it:
    ```bash
    python generate/base.py --prompt "Hello, my name is" --checkpoint_dir ./stablelm-base-alpha-3b --precision 32-true
    ```
2. If the above didn't help try to install the previous version of PyTorch-nightly (perhaps try with a clean venv):
    ```bash
    pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch==2.1.0.dev20230703'
    ```

@Never-up could you report back what option did help you (if any)?

**Comment by Never-up** [comment] 2023-08-15 07:14
> 

thank you for help, first option is usefull

**Comment by JerryDaHeLian** [comment] 2023-11-17 06:16
> Actually it seems like the problem is in the precision (it's `bf16-true` by default) which is not supported by many popular graphics cards like T4 or V100. And previous versions of PyTorch-nightly for some reason didn't care about wrongly provided precision at all.
> 
> So try to solve it in that order:
> 
> 1. Use the proper precision for your graphics card. [Here](https://github.com/Lightning-AI/lit-gpt/blob/96d66b4845ebe287b5dd57b45e584b38d4f660e7/lit_gpt/speed_monitor.py#L17-L57) you can find what precisions are supported.
>    Hint: use `--precision` CLI argument in order to use it:
>    ```shell
>    python generate/base.py --prompt "Hello, my name is" --checkpoint_dir ./stablelm-base-alpha-3b --precision 32-true
>    ```
> 2. If the above didn't help try to install the previous version of PyTorch-nightly (perhaps try with a clean venv):
>    ```shell
>    pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch==2.1.0.dev20230703'
>    ```
> 
> @Never-up could you report back what option did help you (if any)?

However, there is still the following error:
RuntimeError: Expected x1.dtype() == cos.dtype() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)。
