### ISSUE TITLE
Checkpoint File Size After Using `convert_lit_checkpoint`

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-AI/lit-gpt#539] opened 2023-09-12 11:42 UTC
A Discord community member has pointed out that the output of using `convert_lit_checkpoint` is unexpectedly large (~129GB). 

Is this an expected behavior?

**Comment by carmocca** [comment] 2023-09-12 12:17
What's the model size? This will depend on the precision used.

**Comment by JustinGoheen** [comment] 2023-09-12 12:32
It is `Llama-2-70b`

**Comment by carmocca** [comment] 2023-09-12 12:59
70B at half precision (2 bytes) is 140 GB. So the size seems correct. You'll notice that https://huggingface.co/meta-llama/Llama-2-70b-hf/tree/main has 14 `.bin` files of 10 GB each, which matches our 140 GB number.

If anything, the checkpoint is a bit small

**Comment by windprak** [comment] 2023-09-12 13:29
The problem was not about the size. Am I supposed to copy the config files from the Llama-2-70b-hf model? There are no other config files with it. I edited to config files from Llama-2-70b-hf to just support the single file and it worked for inference but with a warning that the files have been edited.

**Comment by windprak** [comment] 2023-09-13 13:06
@JustinGoheen yes, it would be much more convenient to have the matching config files for the fine-tuned model after the conversion. Or at least some documentation on how to create these files. For example: pytorch_model.bin.index.json had to be customized to only support one file instead of 15 in the base model.

**Comment by JustinGoheen** [comment] 2023-09-14 10:28
@windprak just checking that I am understanding correctly so that I can action this.  

are you suggesting that we:

- save a `lit_config`
- save a `finetuning_config`
- save a `conversion_config`

**Comment by carmocca** [comment] 2023-09-20 05:16
Closing this issue as a duplicate of https://github.com/Lightning-AI/lit-gpt/issues/483

**Closed by carmocca** 2023-09-20 05:16 UTC
Labels: question, checkpoints
