### ISSUE TITLE
Can you pretrain llama2 in v100 through the lighting fabric?

### ISSUE THREAD

**Issue by JerryDaHeLian** [Lightning-AI/lit-gpt#737] opened 2023-11-17 06:06 UTC
能在v100 上通过lightning 预训练llama 2 模型吗？

**Comment by carmocca** [comment] 2023-11-17 16:21
Duplicate of https://github.com/Lightning-AI/lit-gpt/issues/740?

**Closed by carmocca** 2023-11-17 16:21 UTC
