### ISSUE TITLE
Weird output by llama2-7b-chat

### ISSUE THREAD

**Issue by hamjam** [Lightning-AI/lit-gpt#452] opened 2023-08-23 04:11 UTC
Hi,
I have downloaded llama2-7b-chat and converted it to huggingface format using [this](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py) script. Then I used below command, as mentioned in [download_llama_2.md](../tree/main/tutorials/download_llama_2.md), 
```bash
python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-chat-hf
```
After installing sentencepiece and using [chat/base.py](../tree/main/chat/base.py), I got weird output for my prompt:
![image](https://github.com/Lightning-AI/lit-gpt/assets/12621752/047dac97-1757-4eda-9a93-90fe73ff2579)

Comparing to huggingface demo for the same prompt:
![image](https://github.com/Lightning-AI/lit-gpt/assets/12621752/bdcb1e16-a954-4d95-afc9-723539d23ff6)

**Comment by OscarIntellico** [comment] 2023-08-24 15:36
Now that i have more time, i'll describe my issue better.
I followed the guide in [download_llama_2.md](https://github.com/Lightning-AI/lit-gpt/tree/main/tutorials/download_llama_2.md) to download the chat version of llama2-7b. Then i convert it to lit-gpt format with the script and when i try to chat with it i get the output that you see in my previous comment.

When trying to run the following command :
`python chat/base.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-chat-hf/ `
i get the following error:
```Traceback (most recent call last):
  File "/home/ubuntu/lit-parrot/chat/base.py", line 304, in <module>
    CLI(main)
  File "/opt/conda/envs/Parrot/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/opt/conda/envs/Parrot/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/ubuntu/lit-parrot/chat/base.py", line 162, in main
    model.load_state_dict(checkpoint.get("model", checkpoint), strict=quantize is None)
  File "/opt/conda/envs/Parrot/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2056, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GPT:
        Unexpected key(s) in state_dict: "transformer.h.16.attn.proj.weight", "transformer.h.16.mlp.fc_1.weight", "transformer.h.16.mlp.fc_2.weight", "transformer.h.16.mlp.proj.weight", "transformer.h.16.norm_1.weight", "transformer.h.16.norm_2.weight", "transformer.h.17.attn.proj.weight", "transformer.h.17.mlp.fc_1.weight", "transformer.h.17.mlp.fc_2.weight", "transformer.h.17.mlp.proj.weight", "transformer.h.17.norm_1.weight", "transformer.h.17.norm_2.weight", "transformer.h.18.attn.proj.weight", "transformer.h.18.mlp.fc_1.weight", "transformer.h.18.mlp.fc_2.weight", "transformer.h.18.mlp.proj.weight", "transformer.h.18.norm_1.weight", "transformer.h.18.norm_2.weight", "transformer.h.19.attn.proj.weight", "transformer.h.19.mlp.fc_1.weight", "transformer.h.19.mlp.fc_2.weight", "transformer.h.19.mlp.proj.weight", "transformer.h.19.norm_1.weight", "transformer.h.19.norm_2.weight", "transformer.h.20.attn.proj.weight", "transformer.h.20.mlp.fc_1.weight", "transformer.h.20.mlp.fc_2.weight", "transformer.h.20.mlp.proj.weight", "transformer.h.20.norm_1.weight", "transformer.h.20.norm_2.weight", "transformer.h.21.attn.proj.weight", "transformer.h.21.mlp.fc_1.weight", "transformer.h.21.mlp.fc_2.weight", "transformer.h.21.mlp.proj.weight", "transformer.h.21.norm_1.weight", "transformer.h.21.norm_2.weight", "transformer.h.22.attn.proj.weight", "transformer.h.22.mlp.fc_1.weight", "transformer.h.22.mlp.fc_2.weight", "transformer.h.22.mlp.proj.weight", "transformer.h.22.norm_1.weight", "transformer.h.22.norm_2.weight", "transformer.h.23.attn.proj.weight", "transformer.h.23.mlp.fc_1.weight", "transformer.h.23.mlp.fc_2.weight", "transformer.h.23.mlp.proj.weight", "transformer.h.23.norm_1.weight", "transformer.h.23.norm_2.weight", "transformer.h.16.attn.attn.weight", "transformer.h.17.attn.attn.weight", "transformer.h.18.attn.attn.weight", "transformer.h.19.attn.attn.weight", "transformer.h.20.attn.attn.weight", "transformer.h.21.attn.attn.weight", "transformer.h.22.attn.attn.weight", "transformer.h.23.attn.attn.weight", "transformer.h.24.attn.proj.weight", "transformer.h.24.mlp.fc_1.weight", "transformer.h.24.mlp.fc_2.weight", "transformer.h.24.mlp.proj.weight", "transformer.h.24.norm_1.weight", "transformer.h.24.norm_2.weight", "transformer.h.25.attn.proj.weight", "transformer.h.25.mlp.fc_1.weight", "transformer.h.25.mlp.fc_2.weight", "transformer.h.25.mlp.proj.weight", "transformer.h.25.norm_1.weight", "transformer.h.25.norm_2.weight", "transformer.h.26.attn.proj.weight", "transformer.h.26.mlp.fc_1.weight", "transformer.h.26.mlp.fc_2.weight", "transformer.h.26.mlp.proj.weight", "transformer.h.26.norm_1.weight", "transformer.h.26.norm_2.weight", "transformer.h.27.attn.proj.weight", "transformer.h.27.mlp.fc_1.weight", "transformer.h.27.mlp.fc_2.weight", "transformer.h.27.mlp.proj.weight", "transformer.h.27.norm_1.weight", "transformer.h.27.norm_2.weight", "transformer.h.28.attn.proj.weight", "transformer.h.28.mlp.fc_1.weight", "transformer.h.28.mlp.fc_2.weight", "transformer.h.28.mlp.proj.weight", "transformer.h.28.norm_1.weight", "transformer.h.28.norm_2.weight", "transformer.h.29.attn.proj.weight", "transformer.h.29.mlp.fc_1.weight", "transformer.h.29.mlp.fc_2.weight", "transformer.h.29.mlp.proj.weight", "transformer.h.29.norm_1.weight", "transformer.h.29.norm_2.weight", "transformer.h.30.attn.proj.weight", "transformer.h.30.mlp.fc_1.weight", "transformer.h.30.mlp.fc_2.weight", "transformer.h.30.mlp.proj.weight", "transformer.h.30.norm_1.weight", "transformer.h.30.norm_2.weight", "transformer.h.31.attn.proj.weight", "transformer.h.31.mlp.fc_1.weight", "transformer.h.31.mlp.fc_2.weight", "transformer.h.31.mlp.proj.weight", "transformer.h.31.norm_1.weight", "transformer.h.31.norm_2.weight", "transformer.h.24.attn.attn.weight", "transformer.h.25.attn.attn.weight", "transformer.h.26.attn.attn.weight", "transformer.h.27.attn.attn.weight", "transformer.h.28.attn.attn.weight", "transformer.h.29.attn.attn.weight", "transformer.h.30.attn.attn.weight", "transformer.h.31.attn.attn.weight". ```

**Comment by JustinGoheen** [comment] 2023-08-25 15:06
maybe this is attributed to the `strict` setting when loading the state_dict in chat/base.py?

**Comment by OscarIntellico** [comment] 2023-08-25 15:50
I've resolved the issue, but I'm still unclear about the root cause. I pulled the PR branch of QLoRA before its integration into the main branch. For some reason, the final layer of the model wasn't saved when converting LLama2-7b-chat-hf in that branch. I'm unsure whether the layers were present with random initialization or if they were missing altogether. As a result, instead of the expected 7B parameters, the model only showed 3.5B. It's surprising that I could still finetune and perform inference with quantization.

I addressed the problem by creating a new branch from the updated main and then copying my files into this new branch.

**Comment by carmocca** [comment] 2023-08-25 17:57
I just ran the top example and it seems to output correctly.

Closing. It might have been a temporary issue with a previous commit.

**Closed by carmocca** 2023-08-25 17:57 UTC
Labels: bug, checkpoints

**Comment by jiasenlu** [comment] 2023-09-16 06:09
It seems the problem is still here with the latest commit. 

```[2023-09-16 06:06:26,617] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-09-16 06:06:27.895183: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading model 'checkpoints/meta-llama/Llama-2-7b-chat-hf/lit_model.pth' with {'org': 'meta-llama', 'name': 'Llama-2-7b-chat-hf', 'block_size': 4096, 'vocab_size': 32000, 'padding_multiple': 64, 'padded_vocab_size': 32000, 'n_layer': 32, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-05, '_mlp_class': 'LLaMAMLP', 'intermediate_size': 11008, 'rope_condense_ratio': 1, 'rope_base': 10000, 'head_size': 128, 'rope_n_elem': 128}
>> Prompt: Write a 100-word article on 'Benefits of Open-Source in AI research'
>> Reply: An open problem in machine learning. A chance to solve a problem in a popular vote in a local election. An opinion poll in a general election. A decision in a constitution in a constitution in a federal system.

Please note that voting is now a choice in a federal election. Choose between a popular vote in a general election.

Please note that a popular vote is now a choice in a federal election. Vote now and vote often in a federal election.

Please note that voting is now a choice in a federal election. Vote now and vote often in a federal election.

Please note that a popular vote is now a choice in a federal election. Vote now and vote often in a federal election.

Subscribable at all times in a popular vote in a federal election. A choice at all times in a federal election.

Please note that voting is now a choice in a federal election. Choose between a popular vote in a general election.```

**Comment by hamjam** [comment] 2023-09-16 07:37
yeah, I still have the issue with the latest commit.

**Comment by carmocca** [comment] 2023-09-16 17:34
This test https://github.com/Lightning-AI/lit-gpt/blob/main/tests/test_model.py#L222 checks for numerical parity with the HF implementation. Perhaps there's a difference in the prompting or a precision issue.
